version: '3'
services:
  qorus:
    image: public.ecr.aws/qorus/qorus-ee:latest
    ports:
    - "8011:8011"
    environment:
      OMQ_DB_NAME: omq
      OMQ_DB_TYPE: pgsql
      OMQ_DB_HOST: pg
      OMQ_DB_USER: omq
      OMQ_DB_PASS: omq
      OMQUSER_DB_NAME: omquser
      OMQUSER_DB_TYPE: pgsql
      OMQUSER_DB_HOST: pg
      OMQUSER_DB_USER: omquser
      OMQUSER_DB_PASS: omquser
      TZ: Europe/Prague
    restart: always
    volumes:
    - ./qorus-etc:/opt/qorus/etc
    - ./qorus-log:/opt/qorus/log
    - ./qorus-user:/opt/qorus/user
    links:
    - pg
    ulimits:
      nproc:
        soft: 8192
        hard: 65536
      nofile:
        soft: 8192
        hard: 32768
  pg:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: omq
      TZ: Europe/Prague
      PGTZ: Europe/Prague
    volumes:
    - ./qorus-postgres-data:/var/lib/postgresql/data
    - ./qorus-postgres-initdb/qorus-setup.sql:/docker-entrypoint-initdb.d/qorus-setup.sql
volumes:
  qorus-etc:
  qorus-log:
  qorus-user:
  qorus-postgres-data:
